# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-11 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dev',
            old_name='street',
            new_name='address',
        ),
    ]
