# Generated by Django 2.1.5 on 2019-02-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_state',
            field=models.CharField(max_length=2),
        ),
    ]
